### ISSUE TITLE
大佬，这个flink-kudu-connector支持checkpoint吗？

### ISSUE THREAD

**Issue by amazingSaltFish** [collabH/flink-connector-kudu#4]
Sink: Sink(table=[default_catalog.default_database.teacher4], fields=[id, name, age]) (1/1) (8ddb33f3da34221584f625438dc18a8c) switched from RUNNING to FAILED on container_1618471122700_0004_01_000002 @ spark1 (dataPort=36997).
java.lang.Exception: Error while triggering checkpoint 1 for Source: TableSourceScan(table=[[default_catalog, default_database, stu4_kafka]], fields=[id, name, age]) -> DropUpdateBefore -> Sink: Sink(table=[default_catalog.default_database.teacher4], fields=[id, name, age]) (1/1)#0
	at org.apache.flink.runtime.taskmanager.Task.triggerCheckpointBarrier(Task.java:1176) ~[Flink_test-1.0-SNAPSHOT.jar:?]
	at org.apache.flink.runtime.taskexecutor.TaskExecutor.triggerCheckpoint(TaskExecutor.java:840) ~[Flink_test-1.0-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:286) ~[Flink_test-1.0-SNAPSHOT.jar:?]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:201) ~[Flink_test-1.0-SNAPSHOT.jar:?]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:154) ~[Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26) [Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21) [Flink_test-1.0-SNAPSHOT.jar:?]
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123) [Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21) [Flink_test-1.0-SNAPSHOT.jar:?]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) [Flink_test-1.0-SNAPSHOT.jar:?]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) [Flink_test-1.0-SNAPSHOT.jar:?]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) [Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517) [Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225) [Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592) [Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.actor.ActorCell.invoke(ActorCell.scala:561) [Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258) [Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:225) [Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235) [Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [Flink_test-1.0-SNAPSHOT.jar:?]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [Flink_test-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.UnsupportedOperationException: triggerCheckpointAsync not supported by org.apache.flink.streaming.runtime.tasks.SourceStreamTask
	at org.apache.flink.runtime.jobgraph.tasks.AbstractInvokable.triggerCheckpointAsync(AbstractInvokable.java:222) ~[Flink_test-1.0-SNAPSHOT.jar:?]
	at org.apache.flink.runtime.taskmanager.Task.triggerCheckpointBarrier(Task.java:1166) ~[Flink_test-1.0-SNAPSHOT.jar:?]
	... 26 more

**Comment by collabH** [comment]
支持的，只不过每次checkpoint只是flush数据和校验错误，并且没有初始化状态的操作

**Comment by collabH** [comment]
@Override
    public void snapshotState(FunctionSnapshotContext functionSnapshotContext) throws Exception {
        kuduWriter.flushAndCheckErrors();
    }

    @Override
    public void initializeState(FunctionInitializationContext functionInitializationContext) throws Exception {
    }

sink端的checkpoint，每次快照回去flush记录落盘，source端没有checkpoint，因为source端是batch读取。

**Comment by amazingSaltFish** [comment]
判定是kafka connector的错误，与大佬写的kudu connector目前没有关系，我先把这个问题解决。感谢大佬的支持。
