### ISSUE TITLE
he number of replicas does not equal the number of servers

### ISSUE THREAD

**Issue by yonghaozhang** [collabH/flink-connector-kudu#9]
您好，我这边总是遇到这样issue, 您知道什么原因么

2021-08-30 21:23:51
java.io.IOException: Error while sending value. 
 Row error for primary key="25", tablet=null, server=null, status=Runtime error: the number of replicas does not equal the number of servers
Row error for primary key="28", tablet=null, server=null, status=Runtime error: the number of replicas does not equal the number of servers

	at org.colloh.flink.kudu.connector.internal.failure.DefaultKuduFailureHandler.onFailure(DefaultKuduFailureHandler.java:37)
	at org.colloh.flink.kudu.connector.internal.writer.KuduWriter.checkAsyncErrors(KuduWriter.java:164)
	at org.colloh.flink.kudu.connector.internal.writer.KuduWriter.checkErrors(KuduWriter.java:154)
	at org.colloh.flink.kudu.connector.internal.writer.KuduWriter.write(KuduWriter.java:108)
	at org.colloh.flink.kudu.connector.table.sink.KuduSink.invoke(KuduSink.java:97)
	at org.apache.flink.streaming.api.functions.sink.SinkFunction.invoke(SinkFunction.java:49)
	at org.apache.flink.table.runtime.operators.sink.SinkOperator.processElement(SinkOperator.java:72)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:46)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:26)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:50)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:28)
	at StreamExecCalc$301.processElement(Unknown Source)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:46)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:26)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:50)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:28)
	at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:50)
	at org.apache.flink.table.runtime.operators.aggregate.GroupAggFunction.processElement(GroupAggFunction.java:194)
	at org.apache.flink.table.runtime.operators.aggregate.GroupAggFunction.processElement(GroupAggFunction.java:43)
	at org.apache.flink.streaming.api.operators.KeyedProcessOperator.processElement(KeyedProcessOperator.java:83)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:187)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.processElement(StreamTaskNetworkInput.java:204)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.emitNext(StreamTaskNetworkInput.java:174)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:395)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:191)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:609)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:573)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:755)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:570)
	at java.lang.Thread.run(Thread.java:748)

我这边看了下 replcas = 3, server =0, 不知道什么原因 server=0

**Comment by yonghaozhang** [comment]
我的 flink sink sql 这样的:
 "CREATE TABLE `i2001__origin_ennenergy_gsm_prod__gs_ex_gas_daily_kudu` (`gas_daily_id` STRING, `daily_date` STRING, `warning_status` STRING, `demand_total` DOUBLE, `demand_resident` DOUBLE, `demand_business` DOUBLE, `demand_traffic` DOUBLE, `demand_traffic_lng` DOUBLE, `demand_traffic_cng` DOUBLE, `demand_heat` DOUBLE, `demand_other` DOUBLE, `today_lng` DOUBLE, `today_cng` DOUBLE, `total_today_report` DOUBLE, `total_today_reply` DOUBLE, `total_yesterday_in` DOUBLE, `total_yesterday_out` DOUBLE, `total_today_forecast` DOUBLE, `forecast_day1` DOUBLE, `forecast_day2` DOUBLE, `forecast_day3` DOUBLE, `forecast_day4` DOUBLE, `forecast_day5` DOUBLE, `forecast_day6` DOUBLE, `yesterday_total` DOUBLE, `yesterday_total_png` DOUBLE, `yesterday_total_lng` DOUBLE, `yesterday_total_cng` DOUBLE, `yesterday_lng_car` DOUBLE, `yesterday_lng_add` DOUBLE, `yesterday_lng_point` DOUBLE, `yesterday_industry` DOUBLE, `yesterday_detail_city` DOUBLE, `yesterday_detail_traffic_lng` DOUBLE, `yesterday_detail_traffic_cng` DOUBLE, `yesterday_detail_export` DOUBLE, `yesterday_log` STRING, `status` STRING, `company_code` STRING, `first_submit_user` STRING, `first_submit_date` STRING, `remark` STRING, `create_user` STRING, `create_date` STRING, `modified_user` STRING, `modified_date` STRING, `is_deleted` INT) WITH('connector' = 'kudu', 'kudu.masters' = '10.37.54.13:7051,10.37.54.45:7051,10.37.54.12:7051', 'kudu.table' = 'origin_ennenergy_gsm_prod.gs_ex_gas_daily_kudu', 'kudu.hash-columns' = 'gas_daily_id', 'kudu.primary-key-columns' = 'gas_daily_id')"

**Comment by collabH** [comment]
看着像是tablet server的数量小于副本的数量不一致导致的这个问题

**Comment by collabH** [comment]
with里你可以指定下`kudu.replicas`为1

**Comment by yonghaozhang** [comment]
![image](https://user-images.githubusercontent.com/10104711/131520789-b0d353fe-7147-4fae-9777-3f3d30484713.png)
亲， 遇到了tserver timeout的问题，有什么解决思路么

**Comment by yonghaozhang** [comment]
> with里你可以指定下`kudu.replicas`为1

是公司k8s网络 和 kudu虚拟机不同的原因。。。

**Comment by yonghaozhang** [comment]
是公司k8s网络 和 kudu虚拟机不同的原因。。。
